/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { getColorMaterial } from '../../Game';
import * as THREE from 'three';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/resources/king.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={getColorMaterial(props.color)}
        geometry={nodes.Cylinder.geometry}
        position={[0, 0.55, 0]}
        rotation={[0, -Math.PI / 8, 0]}
        scale={new Array(3).fill(0.15)}
      />
    </group>
  )
}

useGLTF.preload('/resources/king.gltf')
